"""empty message

Revision ID: 47d98acfbe9e
Revises: 86751f64c717
Create Date: 2023-10-24 18:50:18.328636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d98acfbe9e'
down_revision = '86751f64c717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabriquant', sa.String(length=128), nullable=True))
        batch_op.drop_column('frabiquant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frabiquant', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('fabriquant')

    # ### end Alembic commands ###
