"""empty message

Revision ID: 86751f64c717
Revises: 0d26a3327d6a
Create Date: 2023-10-20 17:36:15.295947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86751f64c717'
down_revision = '0d26a3327d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_router_update'), ['update'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_router_update'))
        batch_op.drop_column('update')

    # ### end Alembic commands ###
