"""empty message

Revision ID: 8be553807be1
Revises: 
Create Date: 2023-10-19 17:40:09.945678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be553807be1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('frabiquant', sa.String(length=128), nullable=True),
    sa.Column('sous_reseau', sa.String(length=128), nullable=True),
    sa.Column('mac', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=128), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('mdp', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('prenom', sa.String(length=128), nullable=True),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_nom'), ['nom'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nom'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('router')
    # ### end Alembic commands ###
